#!/usr/bin/python 

import sys
import subprocess

if len(sys.argv) != 3:
    print("Usage: compare-releases <release1> <release2>")
    sys.exit(1)

release1 = sys.argv[1]
release2 = sys.argv[2]

diff_file = f"{release1}-{release2}.diff"

diff_cmd = f"git diff {release1} {release2}"
diff_output = subprocess.check_output(diff_cmd, shell=True).decode("utf-8")

with open(diff_file, "w") as f:
    f.write(diff_output)
